gifsicle abe.gif --delete "#-1" > converted\abe.gif
gifsicle acorn.gif --delete "#-1" > converted\acorn.gif
gifsicle americanfootball.gif --delete "#-1" > converted\americanfootball.gif
gifsicle ancientone.gif --delete "#-1" > converted\ancientone.gif
gifsicle angel.gif --delete "#-1" > converted\angel.gif
gifsicle anger.gif --delete "#-1" > converted\anger.gif
gifsicle angry.gif --delete "#-1" > converted\angry.gif
gifsicle aokijump.gif --delete "#-1" > converted\aokijump.gif
gifsicle auld.gif --delete "#-1" > converted\auld.gif
gifsicle avocadolove.gif --delete "#-1" > converted\avocadolove.gif
gifsicle baku2017.gif --delete "#-1" > converted\baku2017.gif
gifsicle bandit.gif --delete "#-1" > converted\bandit.gif
gifsicle bartlett.gif --delete "#-1" > converted\bartlett.gif
gifsicle batcry.gif --delete "#-1" > converted\batcry.gif
gifsicle batsmile.gif --delete "#-1" > converted\batsmile.gif
gifsicle beer.gif --delete "#-1" > converted\beer.gif
gifsicle bell.gif --delete "#-1" > converted\bell.gif
gifsicle bertlett.gif --delete "#-1" > converted\bertlett.gif
gifsicle bhangra.gif --delete "#-1" > converted\bhangra.gif
gifsicle bike.gif --delete "#-1" > converted\bike.gif
gifsicle blackwidow.gif --delete "#-1" > converted\blackwidow.gif
gifsicle blush.gif --delete "#-1" > converted\blush.gif
gifsicle bollylove.gif --delete "#-1" > converted\bollylove.gif
gifsicle bomb.gif --delete "#-1" > converted\bomb.gif
gifsicle bow.gif --delete "#-1" > converted\bow.gif
gifsicle bowled.gif --delete "#-1" > converted\bowled.gif
gifsicle brb.gif --delete "#-1" > converted\brb.gif
gifsicle brokenheart.gif --delete "#-1" > converted\brokenheart.gif
gifsicle bronzemedal.gif --delete "#-1" > converted\bronzemedal.gif
gifsicle bucky.gif --delete "#-1" > converted\bucky.gif
gifsicle bug.gif --delete "#-1" > converted\bug.gif
gifsicle bunny.gif --delete "#-1" > converted\bunny.gif
gifsicle busyday.gif --delete "#-1" > converted\busyday.gif
gifsicle cactuslove.gif --delete "#-1" > converted\cactuslove.gif
gifsicle cake.gif --delete "#-1" > converted\cake.gif
gifsicle cakethrow.gif --delete "#-1" > converted\cakethrow.gif
gifsicle call.gif --delete "#-1" > converted\call.gif
gifsicle camera.gif --delete "#-1" > converted\camera.gif
gifsicle canyoutalk.gif --delete "#-1" > converted\canyoutalk.gif
gifsicle captain.gif --delete "#-1" > converted\captain.gif
gifsicle cash.gif --delete "#-1" > converted\cash.gif
gifsicle cat.gif --delete "#-1" > converted\cat.gif
gifsicle chai.gif --delete "#-1" > converted\chai.gif
gifsicle champagne.gif --delete "#-1" > converted\champagne.gif
gifsicle chappal.gif --delete "#-1" > converted\chappal.gif
gifsicle cheerleader.gif --delete "#-1" > converted\cheerleader.gif
gifsicle cheers.gif --delete "#-1" > converted\cheers.gif
gifsicle cheese.gif --delete "#-1" > converted\cheese.gif
gifsicle chicksegg.gif --delete "#-1" > converted\chicksegg.gif
gifsicle clap.gif --delete "#-1" > converted\clap.gif
gifsicle coffee.gif --delete "#-1" > converted\coffee.gif
gifsicle computer.gif --delete "#-1" > converted\computer.gif
gifsicle computerrage.gif --delete "#-1" > converted\computerrage.gif
gifsicle confidential.gif --delete "#-1" > converted\confidential.gif
gifsicle cool.gif --delete "#-1" > converted\cool.gif
gifsicle coutinho10.gif --delete "#-1" > converted\coutinho10.gif
gifsicle cry.gif --delete "#-1" > converted\cry.gif
gifsicle cupcake.gif --delete "#-1" > converted\cupcake.gif
gifsicle cwl.gif --delete "#-1" > converted\cwl.gif
gifsicle dadtime.gif --delete "#-1" > converted\dadtime.gif
gifsicle dance.gif --delete "#-1" > converted\dance.gif
gifsicle deadyes.gif --delete "#-1" > converted\deadyes.gif
gifsicle devil.gif --delete "#-1" > converted\devil.gif
gifsicle dhakkan.gif --delete "#-1" > converted\dhakkan.gif
gifsicle discodancer.gif --delete "#-1" > converted\discodancer.gif
gifsicle disgust.gif --delete "#-1" > converted\disgust.gif
gifsicle diwaliselfie.gif --delete "#-1" > converted\diwaliselfie.gif
gifsicle diya.gif --delete "#-1" > converted\diya.gif
gifsicle doctorstrange.gif --delete "#-1" > converted\doctorstrange.gif
gifsicle dog.gif --delete "#-1" > converted\dog.gif
gifsicle doh.gif --delete "#-1" > converted\doh.gif
gifsicle donkey.gif --delete "#-1" > converted\donkey.gif
gifsicle donttalktome.gif --delete "#-1" > converted\donttalktome.gif
gifsicle dotdfemale.gif --delete "#-1" > converted\dotdfemale.gif
gifsicle dotdmale.gif --delete "#-1" > converted\dotdmale.gif
gifsicle dracula.gif --delete "#-1" > converted\dracula.gif
gifsicle dream.gif --delete "#-1" > converted\dream.gif
gifsicle dreidel.gif --delete "#-1" > converted\dreidel.gif
gifsicle drink.gif --delete "#-1" > converted\drink.gif
gifsicle drunk.gif --delete "#-1" > converted\drunk.gif
gifsicle dull.gif --delete "#-1" > converted\dull.gif
gifsicle eg.gif --delete "#-1" > converted\eg.gif
gifsicle eid.gif --delete "#-1" > converted\eid.gif
gifsicle emo.gif --delete "#-1" > converted\emo.gif
gifsicle envy.gif --delete "#-1" > converted\envy.gif
gifsicle facepalm.gif --delete "#-1" > converted\facepalm.gif
gifsicle fallinlove.gif --delete "#-1" > converted\fallinlove.gif
gifsicle familytime.gif --delete "#-1" > converted\familytime.gif
gifsicle fear.gif --delete "#-1" > converted\fear.gif
gifsicle festiveparty.gif --delete "#-1" > converted\festiveparty.gif
gifsicle finger.gif --delete "#-1" > converted\finger.gif
gifsicle fingerscrossed.gif --delete "#-1" > converted\fingerscrossed.gif
gifsicle fireworks.gif --delete "#-1" > converted\fireworks.gif
gifsicle fistbump.gif --delete "#-1" > converted\fistbump.gif
gifsicle flower.gif --delete "#-1" > converted\flower.gif
gifsicle footballfail.gif --delete "#-1" > converted\footballfail.gif
gifsicle frankenstein.gif --delete "#-1" > converted\frankenstein.gif
gifsicle fubar.gif --delete "#-1" > converted\fubar.gif
gifsicle games.gif --delete "#-1" > converted\games.gif
gifsicle ganesh.gif --delete "#-1" > converted\ganesh.gif
gifsicle ghost.gif --delete "#-1" > converted\ghost.gif
gifsicle gift.gif --delete "#-1" > converted\gift.gif
gifsicle giggle.gif --delete "#-1" > converted\giggle.gif
gifsicle goldmedal.gif --delete "#-1" > converted\goldmedal.gif
gifsicle golmaal.gif --delete "#-1" > converted\golmaal.gif
gifsicle goodluck.gif --delete "#-1" > converted\goodluck.gif
gifsicle gottarun.gif --delete "#-1" > converted\gottarun.gif
gifsicle gran.gif --delete "#-1" > converted\gran.gif
gifsicle handshake.gif --delete "#-1" > converted\handshake.gif
gifsicle handsinair.gif --delete "#-1" > converted\handsinair.gif
gifsicle happy.gif --delete "#-1" > converted\happy.gif
gifsicle headbang.gif --delete "#-1" > converted\headbang.gif
gifsicle headphones.gif --delete "#-1" > converted\headphones.gif
gifsicle heart.gif --delete "#-1" > converted\heart.gif
gifsicle hearteyes.gif --delete "#-1" > converted\hearteyes.gif
gifsicle hearthands.gif --delete "#-1" > converted\hearthands.gif
gifsicle hedgehog.gif --delete "#-1" > converted\hedgehog.gif
gifsicle heidy.gif --delete "#-1" > converted\heidy.gif
gifsicle hendance.gif --delete "#-1" > converted\hendance.gif
gifsicle henderson14.gif --delete "#-1" > converted\henderson14.gif
gifsicle hero.gif --delete "#-1" > converted\hero.gif
gifsicle heston.gif --delete "#-1" > converted\heston.gif
gifsicle hestonfacepalm.gif --delete "#-1" > converted\hestonfacepalm.gif
gifsicle hi.gif --delete "#-1" > converted\hi.gif
gifsicle highfive.gif --delete "#-1" > converted\highfive.gif
gifsicle holdon.gif --delete "#-1" > converted\holdon.gif
gifsicle holi.gif --delete "#-1" > converted\holi.gif
gifsicle holidayspirit.gif --delete "#-1" > converted\holidayspirit.gif
gifsicle hollest.gif --delete "#-1" > converted\hollest.gif
gifsicle hotchocolate.gif --delete "#-1" > converted\hotchocolate.gif
gifsicle hug.gif --delete "#-1" > converted\hug.gif
gifsicle hungover.gif --delete "#-1" > converted\hungover.gif
gifsicle hungrycat.gif --delete "#-1" > converted\hungrycat.gif
gifsicle iaaf2017.gif --delete "#-1" > converted\iaaf2017.gif
gifsicle iaafjump.gif --delete "#-1" > converted\iaafjump.gif
gifsicle iaafrun.gif --delete "#-1" > converted\iaafrun.gif
gifsicle iaafthrow.gif --delete "#-1" > converted\iaafthrow.gif
gifsicle idea.gif --delete "#-1" > converted\idea.gif
gifsicle ill.gif --delete "#-1" > converted\ill.gif
gifsicle inlove.gif --delete "#-1" > converted\inlove.gif
gifsicle island.gif --delete "#-1" > converted\island.gif
gifsicle jekyllandhyde.gif --delete "#-1" > converted\jekyllandhyde.gif
gifsicle joy.gif --delete "#-1" > converted\joy.gif
gifsicle kaanpakadna.gif --delete "#-1" > converted\kaanpakadna.gif
gifsicle kaecilius.gif --delete "#-1" > converted\kaecilius.gif
gifsicle karlmordo.gif --delete "#-1" > converted\karlmordo.gif
gifsicle key.gif --delete "#-1" > converted\key.gif
gifsicle kiss.gif --delete "#-1" > converted\kiss.gif
gifsicle klopp.gif --delete "#-1" > converted\klopp.gif
gifsicle kolony.gif --delete "#-1" > converted\kolony.gif
gifsicle kya.gif --delete "#-1" > converted\kya.gif
gifsicle laddu.gif --delete "#-1" > converted\laddu.gif
gifsicle ladyvampire.gif --delete "#-1" > converted\ladyvampire.gif
gifsicle lalala.gif --delete "#-1" > converted\lalala.gif
gifsicle lamb.gif --delete "#-1" > converted\lamb.gif
gifsicle lang.gif --delete "#-1" > converted\lang.gif
gifsicle laugh.gif --delete "#-1" > converted\laugh.gif
gifsicle learn.gif --delete "#-1" > converted\learn.gif
gifsicle letsmeet.gif --delete "#-1" > converted\letsmeet.gif
gifsicle lfcclap.gif --delete "#-1" > converted\lfcclap.gif
gifsicle lfcfacepalm.gif --delete "#-1" > converted\lfcfacepalm.gif
gifsicle lfclaugh.gif --delete "#-1" > converted\lfclaugh.gif
gifsicle lfcparty.gif --delete "#-1" > converted\lfcparty.gif
gifsicle lfcworried.gif --delete "#-1" > converted\lfcworried.gif
gifsicle like.gif --delete "#-1" > converted\like.gif
gifsicle lips.gif --delete "#-1" > converted\lips.gif
gifsicle lipssealed.gif --delete "#-1" > converted\lipssealed.gif
gifsicle listening.gif --delete "#-1" > converted\listening.gif
gifsicle llsshock.gif --delete "#-1" > converted\llsshock.gif
gifsicle mail.gif --delete "#-1" > converted\mail.gif
gifsicle makeup.gif --delete "#-1" > converted\makeup.gif
gifsicle malthe.gif --delete "#-1" > converted\malthe.gif
gifsicle man.gif --delete "#-1" > converted\man.gif
gifsicle manshrug.gif --delete "#-1" > converted\manshrug.gif
gifsicle mariachilove.gif --delete "#-1" > converted\mariachilove.gif
gifsicle mistletoe.gif --delete "#-1" > converted\mistletoe.gif
gifsicle mlt.gif --delete "#-1" > converted\mlt.gif
gifsicle mmm.gif --delete "#-1" > converted\mmm.gif
gifsicle monkey.gif --delete "#-1" > converted\monkey.gif
gifsicle monkeygiggle.gif --delete "#-1" > converted\monkeygiggle.gif
gifsicle mooning.gif --delete "#-1" > converted\mooning.gif
gifsicle movember.gif --delete "#-1" > converted\movember.gif
gifsicle movie.gif --delete "#-1" > converted\movie.gif
gifsicle movinghome.gif --delete "#-1" > converted\movinghome.gif
gifsicle mummy.gif --delete "#-1" > converted\mummy.gif
gifsicle mummywalk.gif --delete "#-1" > converted\mummywalk.gif
gifsicle muscle.gif --delete "#-1" > converted\muscle.gif
gifsicle muscleman.gif --delete "#-1" > converted\muscleman.gif
gifsicle music.gif --delete "#-1" > converted\music.gif
gifsicle nahi.gif --delete "#-1" > converted\nahi.gif
gifsicle naturescall.gif --delete "#-1" > converted\naturescall.gif
gifsicle nazar.gif --delete "#-1" > converted\nazar.gif
gifsicle neil.gif --delete "#-1" > converted\neil.gif
gifsicle nerdy.gif --delete "#-1" > converted\nerdy.gif
gifsicle nestingeggs.gif --delete "#-1" > converted\nestingeggs.gif
gifsicle nickfury.gif --delete "#-1" > converted\nickfury.gif
gifsicle ninja.gif --delete "#-1" > converted\ninja.gif
gifsicle no.gif --delete "#-1" > converted\no.gif
gifsicle nod.gif --delete "#-1" > converted\nod.gif
gifsicle noworries.gif --delete "#-1" > converted\noworries.gif
gifsicle ok.gif --delete "#-1" > converted\ok.gif
gifsicle oliver.gif --delete "#-1" > converted\oliver.gif
gifsicle ontheloo.gif --delete "#-1" > converted\ontheloo.gif
gifsicle oye.gif --delete "#-1" > converted\oye.gif
gifsicle party.gif --delete "#-1" > converted\party.gif
gifsicle penguin.gif --delete "#-1" > converted\penguin.gif
gifsicle penguinkiss.gif --delete "#-1" > converted\penguinkiss.gif
gifsicle phone.gif --delete "#-1" > converted\phone.gif
gifsicle pig.gif --delete "#-1" > converted\pig.gif
gifsicle piggybank.gif --delete "#-1" > converted\piggybank.gif
gifsicle pizza.gif --delete "#-1" > converted\pizza.gif
gifsicle plane.gif --delete "#-1" > converted\plane.gif
gifsicle poke.gif --delete "#-1" > converted\poke.gif
gifsicle polarbear.gif --delete "#-1" > converted\polarbear.gif
gifsicle poolparty.gif --delete "#-1" > converted\poolparty.gif
gifsicle poop.gif --delete "#-1" > converted\poop.gif
gifsicle praying.gif --delete "#-1" > converted\praying.gif
gifsicle priidu.gif --delete "#-1" > converted\priidu.gif
gifsicle promise.gif --delete "#-1" > converted\promise.gif
gifsicle puke.gif --delete "#-1" > converted\puke.gif
gifsicle pullshot.gif --delete "#-1" > converted\pullshot.gif
gifsicle pumpkin.gif --delete "#-1" > converted\pumpkin.gif
gifsicle punch.gif --delete "#-1" > converted\punch.gif
gifsicle rain.gif --delete "#-1" > converted\rain.gif
gifsicle rainbow.gif --delete "#-1" > converted\rainbow.gif
gifsicle rainbowsmile.gif --delete "#-1" > converted\rainbowsmile.gif
gifsicle red.gif --delete "#-1" > converted\red.gif
gifsicle reindeer.gif --delete "#-1" > converted\reindeer.gif
gifsicle rickshaw.gif --delete "#-1" > converted\rickshaw.gif
gifsicle ring.gif --delete "#-1" > converted\ring.gif
gifsicle rock.gif --delete "#-1" > converted\rock.gif
gifsicle rockchick.gif --delete "#-1" > converted\rockchick.gif
gifsicle rofl.gif --delete "#-1" > converted\rofl.gif
gifsicle running.gif --delete "#-1" > converted\running.gif
gifsicle sad.gif --delete "#-1" > converted\sad.gif
gifsicle sadness.gif --delete "#-1" > converted\sadness.gif
gifsicle santa.gif --delete "#-1" > converted\santa.gif
gifsicle santamooning.gif --delete "#-1" > converted\santamooning.gif
gifsicle sarcastic.gif --delete "#-1" > converted\sarcastic.gif
gifsicle selfie.gif --delete "#-1" > converted\selfie.gif
gifsicle selfiediwali.gif --delete "#-1" > converted\selfiediwali.gif
gifsicle shake.gif --delete "#-1" > converted\shake.gif
gifsicle sheep.gif --delete "#-1" > converted\sheep.gif
gifsicle shielddeflect.gif --delete "#-1" > converted\shielddeflect.gif
gifsicle shivering.gif --delete "#-1" > converted\shivering.gif
gifsicle shock.gif --delete "#-1" > converted\shock.gif
gifsicle shopping.gif --delete "#-1" > converted\shopping.gif
gifsicle silvermedal.gif --delete "#-1" > converted\silvermedal.gif
gifsicle skate.gif --delete "#-1" > converted\skate.gif
gifsicle skip.gif --delete "#-1" > converted\skip.gif
gifsicle skipping.gif --delete "#-1" > converted\skipping.gif
gifsicle skull.gif --delete "#-1" > converted\skull.gif
gifsicle slamdunk.gif --delete "#-1" > converted\slamdunk.gif
gifsicle slap.gif --delete "#-1" > converted\slap.gif
gifsicle sleepy.gif --delete "#-1" > converted\sleepy.gif
gifsicle sloth.gif --delete "#-1" > converted\sloth.gif
gifsicle smile.gif --delete "#-1" > converted\smile.gif
gifsicle smirk.gif --delete "#-1" > converted\smirk.gif
gifsicle smoke.gif --delete "#-1" > converted\smoke.gif
gifsicle snail.gif --delete "#-1" > converted\snail.gif
gifsicle snowangel.gif --delete "#-1" > converted\snowangel.gif
gifsicle snowflake.gif --delete "#-1" > converted\snowflake.gif
gifsicle sparkler.gif --delete "#-1" > converted\sparkler.gif
gifsicle speechless.gif --delete "#-1" > converted\speechless.gif
gifsicle star.gif --delete "#-1" > converted\star.gif
gifsicle steveaoki.gif --delete "#-1" > converted\steveaoki.gif
gifsicle stingray.gif --delete "#-1" > converted\stingray.gif
gifsicle stop.gif --delete "#-1" > converted\stop.gif
gifsicle sturridge15.gif --delete "#-1" > converted\sturridge15.gif
gifsicle sun.gif --delete "#-1" > converted\sun.gif
gifsicle surprised.gif --delete "#-1" > converted\surprised.gif
gifsicle suryannamaskar.gif --delete "#-1" > converted\suryannamaskar.gif
gifsicle swear.gif --delete "#-1" > converted\swear.gif
gifsicle sweat.gif --delete "#-1" > converted\sweat.gif
gifsicle synchswim.gif --delete "#-1" > converted\synchswim.gif
gifsicle syne.gif --delete "#-1" > converted\syne.gif
gifsicle talk.gif --delete "#-1" > converted\talk.gif
gifsicle talktothehand.gif --delete "#-1" > converted\talktothehand.gif
gifsicle tandoorichicken.gif --delete "#-1" > converted\tandoorichicken.gif
gifsicle target.gif --delete "#-1" > converted\target.gif
gifsicle taur.gif --delete "#-1" > converted\taur.gif
gifsicle tauri.gif --delete "#-1" > converted\tauri.gif
gifsicle tennisfail.gif --delete "#-1" > converted\tennisfail.gif
gifsicle thanks.gif --delete "#-1" > converted\thanks.gif
gifsicle think.gif --delete "#-1" > converted\think.gif
gifsicle time.gif --delete "#-1" > converted\time.gif
gifsicle tired.gif --delete "#-1" > converted\tired.gif
gifsicle tmi.gif --delete "#-1" > converted\tmi.gif
gifsicle toivo.gif --delete "#-1" > converted\toivo.gif
gifsicle tongueout.gif --delete "#-1" > converted\tongueout.gif
gifsicle trampoline.gif --delete "#-1" > converted\trampoline.gif
gifsicle trophy.gif --delete "#-1" > converted\trophy.gif
gifsicle ttm.gif --delete "#-1" > converted\ttm.gif
gifsicle tubelight.gif --delete "#-1" > converted\tubelight.gif
gifsicle tumbleweed.gif --delete "#-1" > converted\tumbleweed.gif
gifsicle turkey.gif --delete "#-1" > converted\turkey.gif
gifsicle tvbinge.gif --delete "#-1" > converted\tvbinge.gif
gifsicle umbrella.gif --delete "#-1" > converted\umbrella.gif
gifsicle unamused.gif --delete "#-1" > converted\unamused.gif
gifsicle unicorn.gif --delete "#-1" > converted\unicorn.gif
gifsicle unsee.gif --delete "#-1" > converted\unsee.gif
gifsicle vampire.gif --delete "#-1" > converted\vampire.gif
gifsicle victory.gif --delete "#-1" > converted\victory.gif
gifsicle wait.gif --delete "#-1" > converted\wait.gif
gifsicle waiting.gif --delete "#-1" > converted\waiting.gif
gifsicle wasntme.gif --delete "#-1" > converted\wasntme.gif
gifsicle webheart.gif --delete "#-1" > converted\webheart.gif
gifsicle werewolf.gif --delete "#-1" > converted\werewolf.gif
gifsicle werewolfhowl.gif --delete "#-1" > converted\werewolfhowl.gif
gifsicle wfh.gif --delete "#-1" > converted\wfh.gif
gifsicle whatsgoingon.gif --delete "#-1" > converted\whatsgoingon.gif
gifsicle whew.gif --delete "#-1" > converted\whew.gif
gifsicle whistle.gif --delete "#-1" > converted\whistle.gif
gifsicle whosthis.gif --delete "#-1" > converted\whosthis.gif
gifsicle win10.gif --delete "#-1" > converted\win10.gif
gifsicle wink.gif --delete "#-1" > converted\wink.gif
gifsicle winner.gif --delete "#-1" > converted\winner.gif
gifsicle witch.gif --delete "#-1" > converted\witch.gif
gifsicle woman.gif --delete "#-1" > converted\woman.gif
gifsicle womanshrug.gif --delete "#-1" > converted\womanshrug.gif
gifsicle wonder.gif --delete "#-1" > converted\wonder.gif
gifsicle wong.gif --delete "#-1" > converted\wong.gif
gifsicle worry.gif --delete "#-1" > converted\worry.gif
gifsicle wtf.gif --delete "#-1" > converted\wtf.gif
gifsicle xmastree.gif --delete "#-1" > converted\xmastree.gif
gifsicle yawn.gif --delete "#-1" > converted\yawn.gif
gifsicle yes.gif --delete "#-1" > converted\yes.gif
gifsicle yoga.gif --delete "#-1" > converted\yoga.gif
gifsicle yotfr.gif --delete "#-1" > converted\yotfr.gif
gifsicle yotm.gif --delete "#-1" > converted\yotm.gif
gifsicle zombie.gif --delete "#-1" > converted\zombie.gif
gifsicle zombiedrool.gif --delete "#-1" > converted\zombiedrool.gif
gifsicle zombiewave.gif --delete "#-1" > converted\zombiewave.gif